params:
  seed: 42
  env:
    clip_actions: 1.0
  algo:
    name: a2c_continuous
  model:
    name: continuous_a2c_logstd
  network:
    name: actor_critic
    separate: false
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: true
    mlp:
      units:
      - 128
      - 128
      - 128
      activation: elu
      d2rl: false
      initializer:
        name: default
      regularizer:
        name: None
  load_checkpoint: false
  load_path: ''
  config:
    name: omniquad_flat
    env_name: rlgpu
    device: cuda:0
    device_name: cuda:0
    multi_gpu: false
    ppo: true
    mixed_precision: true
    normalize_input: false
    normalize_value: true
    value_bootstrap: true
    num_actors: -1
    reward_shaper:
      scale_value: 0.6
    normalize_advantage: true
    gamma: 0.99
    tau: 0.95
    learning_rate: 1e-3
    lr_schedule: adaptive
    schedule_type: legacy
    kl_threshold: 0.01
    score_to_win: 20000
    max_epochs: 10000
    save_best_after: 100
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.005
    truncate_grads: true
    e_clip: 0.2
    horizon_length: 24
    minibatch_size: 24576
    mini_epochs: 5
    critic_coef: 2.0
    clip_value: true
    seq_length: 4
    bounds_loss_coef: 0.0
    train_dir: /home/simone/IsaacLab/logs/rl_games/omniquad_flat
    full_experiment_name: 2025-07-22_13-45-01
