# config.yaml

inference_controller:
  ros__parameters:
    joint_state_topic: "/state_broadcaster/joints_state_forced"
    imu_topic: "/IMU_Broadcaster/imu_forced"                    #Takes from force_measure node
    joint_target_pos_topic: "/PD_control/command"
    cmd_vel_topic: "/cmd_vel"
    rate: 100 # Hz
    use_imu: True
    use_sim_time: False
    simulation: True
