controller_manager:
  ros__parameters:
    imu_topic: "/omnicar/imu"

    update_rate: 250 # Hz

    joint_state_broadcaster_1:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    ik_leg:
      type: ik_quad_foot_control/IK_Quad_Foot_Controller
      
    # omni_control:
    #   type: omni_vel_controller/OmniVelController 

    wheels_vel_controller:
      type: wheels_vel_cnt/WheelsVelCnt

    pd_controller:
      type: rbt_pd_cnt/Rbt_PD_cnt


joint_state_broadcaster_1:
  ros__parameters:
    joints:
      - LF_HFE
      - LH_HFE
      - RF_HFE
      - RH_HFE
      - joint_wheel_1_LEFT_F
      - joint_wheel_2_LEFT_F
      - joint_wheel_3_LEFT_F
      - joint_wheel_4_LEFT_F
      - joint_wheel_1_LEFT_H
      - joint_wheel_2_LEFT_H
      - joint_wheel_3_LEFT_H
      - joint_wheel_4_LEFT_H
      - joint_wheel_1_RIGHT_F
      - joint_wheel_2_RIGHT_F
      - joint_wheel_3_RIGHT_F
      - joint_wheel_4_RIGHT_F
      - joint_wheel_1_RIGHT_H
      - joint_wheel_2_RIGHT_H
      - joint_wheel_3_RIGHT_H
      - joint_wheel_4_RIGHT_H
      - body_left_F_ankle
      - body_left_H_ankle
      - body_right_F_ankle
      - body_right_H_ankle
    use_sim_time: True

ik_leg:
  ros__parameters:
      homing_pos: [0.095,-0.095,-0.095,0.095]
      homing_dur: 5.0
      pushup_height: -0.25
      pushup_dur: 3.0
      x_pos_bound: 0.2
      z_pos_bound: 0.35
      init_feet_pos_x: -0.02375
      init_feet_pos_z: -0.25
      use_sim_time: True

wheels_vel_controller:
  ros__parameters:
    joints:
      - joint_wheel_1_LEFT_F
      - joint_wheel_2_LEFT_F
      - joint_wheel_3_LEFT_F
      - joint_wheel_4_LEFT_F
      - joint_wheel_1_LEFT_H
      - joint_wheel_2_LEFT_H
      - joint_wheel_3_LEFT_H
      - joint_wheel_4_LEFT_H
      - joint_wheel_1_RIGHT_F
      - joint_wheel_2_RIGHT_F
      - joint_wheel_3_RIGHT_F
      - joint_wheel_4_RIGHT_F
      - joint_wheel_1_RIGHT_H
      - joint_wheel_2_RIGHT_H
      - joint_wheel_3_RIGHT_H
      - joint_wheel_4_RIGHT_H
    use_sim_time: True

# omni_control:
#   ros__parameters:
#     mecanum_angle: 135.0
#     wheel_rad: 0.03875
#     pub_odom: true
#     sim: true

pd_controller:
  ros__parameters:
    joint:
      - LF_HFE        # Left HIP Front
      - LH_HFE        # Left HIP Back
      - RF_HFE        # Right HIP Front
      - RH_HFE        # Right HIP Back
      # - LF_WHEEL_JNT    
      # - LH_WHEEL_JNT
      # - RF_WHEEL_JNT
      # - RH_WHEEL_JNT
      
 
    K_d:
      - 10.0
      - 10.0
      - 10.0
      - 10.0



      
    K_p:
      - 100.0
      - 100.0
      - 100.0
      - 100.0


     
 
 # Nota: Hip: 120° = 2.094 rad, Knee: 60° = 1.047 rad
    init_pos:   # NOTA! Mettere init_pos diverso da 0 
      - 1.13
      - -1.13
      - -1.13
      - 1.13
    use_sim_time: True