controller_manager:
  ros__parameters:
    update_rate: 340 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    omni_control:
      type: omni_vel_controller/OmniVelController


joint_state_broadcaster:
  ros__parameters:
    joints:
      - LF_WHEEL_JNT
      - LH_WHEEL_JNT
      - RF_WHEEL_JNT
      - RH_WHEEL_JNT

    use_sim_time: True

omni_control:
  ros__parameters:
    mecanum_angle: 135.0
    wheel_rad: 0.03875
    pub_odom: false
    sim: true
    use_sim_time: True

    joints:
      - LF_WHEEL_JNT
      - LH_WHEEL_JNT
      - RF_WHEEL_JNT
      - RH_WHEEL_JNT
    wheels:
      - LF_WHEEL
      - LH_WHEEL
      - RF_WHEEL
      - RH_WHEEL